# Generated by Django 3.2 on 2022-06-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_stock_id_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
    ]
